-- Drop tables with FORCE (via EXECUTE IMMEDIATE)
BEGIN
  BEGIN EXECUTE IMMEDIATE 'DROP TABLE Leaderships CASCADE CONSTRAINTS PURGE';    EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'DROP TABLE ARevenues CASCADE CONSTRAINTS PURGE';      EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'DROP TABLE AExpenses CASCADE CONSTRAINTS PURGE';      EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'DROP TABLE Periods CASCADE CONSTRAINTS PURGE';        EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'DROP TABLE Municipalities CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'DROP TABLE GeoEntities CASCADE CONSTRAINTS PURGE';    EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'DROP TABLE Headings CASCADE CONSTRAINTS PURGE';       EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'DROP TABLE Parties CASCADE CONSTRAINTS PURGE';        EXCEPTION WHEN OTHERS THEN NULL; END;
END;
/

-- Drop types with FORCE
DROP TYPE Municipality_T FORCE;
DROP TYPE LeadershipList_T FORCE;
DROP TYPE Leadership_T FORCE;
DROP TYPE BudgetList_T FORCE;
DROP TYPE BudgetEntry_T FORCE;
DROP TYPE Period_T FORCE;
DROP TYPE Heading_RefList_T FORCE;
DROP TYPE Heading_T FORCE;
DROP TYPE GeoEntity_T FORCE;
DROP TYPE Party_T FORCE;
