-- Drop tables first (in reverse dependency order)
BEGIN
  BEGIN EXECUTE IMMEDIATE 'DROP TABLE Leaderships'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'DROP TABLE ARevenues';   EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'DROP TABLE AExpenses';   EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'DROP TABLE Periods';     EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'DROP TABLE GeoEntities'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'DROP TABLE Headings';    EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'DROP TABLE Parties';     EXCEPTION WHEN OTHERS THEN NULL; END;
END;
/

DROP TYPE Municipality_T FORCE;
DROP TYPE ExpenseList_T FORCE;
DROP TYPE RevenueList_T FORCE;
DROP TYPE AExpense_T FORCE;
DROP TYPE ARevenue_T FORCE;
DROP TYPE AnnualRecord_T FORCE;
DROP TYPE Heading_T FORCE;
DROP TYPE GeoEntity_T FORCE;
DROP TYPE Party_T FORCE;
