CREATE TABLE ydistritos AS SELECT * FROM GTD7.distritos;
CREATE TABLE yconcelhos AS SELECT * FROM GTD7.concelhos;
CREATE TABLE yfreguesias AS SELECT * FROM GTD7.freguesias;
CREATE TABLE ypartidos AS SELECT * FROM GTD7.partidos;
CREATE TABLE yvotacoes AS SELECT * FROM GTD7.votacoes;
CREATE TABLE ylistas AS SELECT * FROM GTD7.listas;
CREATE TABLE yparticipacoes AS SELECT * FROM GTD7.participacoes;

ALTER TABLE "YDISTRITOS" ADD CONSTRAINT YDISTRITOS_CODIGO_PK PRIMARY KEY("CODIGO");
ALTER TABLE "YCONCELHOS" ADD CONSTRAINT YCONCELHOS_CODIGO_PK PRIMARY KEY("CODIGO");
ALTER TABLE "YFREGUESIAS" ADD CONSTRAINT YFREGUESIAS_CODIGO_PK PRIMARY KEY("CODIGO");
ALTER TABLE "YPARTIDOS" ADD CONSTRAINT YPARTIDOS_SIGLA_PK PRIMARY KEY("SIGLA");
ALTER TABLE "YVOTACOES" ADD CONSTRAINT YVOTACOES_PARTIDO_FREGUESIA_PK PRIMARY KEY("PARTIDO", "FREGUESIA");
ALTER TABLE "YLISTAS" ADD CONSTRAINT YLISTAS_DISTRITO_PARTIDO_PK PRIMARY KEY("DISTRITO", "PARTIDO");
ALTER TABLE "YPARTICIPACOES" ADD CONSTRAINT YPARTICIPACOES_DISTRITO_PK PRIMARY KEY("DISTRITO");

ALTER TABLE "YCONCELHOS" 
ADD CONSTRAINT YCONCELHOS_DISTRITO_FK FOREIGN KEY("DISTRITO") REFERENCES "YDISTRITOS"("CODIGO");

ALTER TABLE "YFREGUESIAS" 
ADD CONSTRAINT YFREGUESIAS_CONCELHO_FK FOREIGN KEY("CONCELHO") REFERENCES "YCONCELHOS"("CODIGO");

ALTER TABLE "YVOTACOES" 
ADD CONSTRAINT YVOTACOES_PARTIDO_FK FOREIGN KEY("PARTIDO") REFERENCES "YPARTIDOS"("SIGLA"),
ADD CONSTRAINT YVOTACOES_FREGUESIA_FK FOREIGN KEY("FREGUESIA") REFERENCES "YFREGUESIAS"("CODIGO");

ALTER TABLE "YLISTAS" 
ADD CONSTRAINT YLISTAS_DISTRITO_FK FOREIGN KEY("DISTRITO") REFERENCES "YDISTRITOS"("CODIGO"),
ADD CONSTRAINT YLISTAS_PARTIDO_FK FOREIGN KEY("PARTIDO") REFERENCES "YPARTIDOS"("SIGLA");

ALTER TABLE "YPARTICIPACOES" 
ADD CONSTRAINT YPARTICIPACOES_DISTRITO_FK FOREIGN KEY("DISTRITO") REFERENCES "YDISTRITOS"("CODIGO");

-- DROP
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE yparticipacoes CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE ylistas CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE yvotacoes CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE ypartidos CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE yfreguesias CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE yconcelhos CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE ydistritos CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('One or more tables did not exist or failed to drop.');
END;
/