CREATE TABLE zdistritos AS SELECT * FROM GTD7.distritos;
CREATE TABLE zconcelhos AS SELECT * FROM GTD7.conselhos;
CREATE TABLE zfreguesias AS SELECT * FROM GTD7.freguesias;
CREATE TABLE zpartidos AS SELECT * FROM GTD7.partidos;
CREATE TABLE zvotacoes AS SELECT * FROM GTD7.votacoes;
CREATE TABLE zlistas AS SELECT * FROM GTD7.listas;
CREATE TABLE zparticipacoes AS SELECT * FROM GTD7.participacoes;

ALTER TABLE "ZDISTRITOS" ADD CONSTRAINT ZDISTRITOS_CODIGO_PK PRIMARY KEY("CODIGO");
ALTER TABLE "ZCONCELHOS" ADD CONSTRAINT ZCONCELHOS_CODIGO_PK PRIMARY KEY("CODIGO");
ALTER TABLE "ZFREGUESIAS" ADD CONSTRAINT ZFREGUESIAS_CODIGO_PK PRIMARY KEY("CODIGO");
ALTER TABLE "ZPARTIDOS" ADD CONSTRAINT ZPARTIDOS_SIGLA_PK PRIMARY KEY("SIGLA");
ALTER TABLE "ZVOTACOES" ADD CONSTRAINT ZVOTACOES_PARTIDO_FREGUESIA_PK PRIMARY KEY("PARTIDO", "FREGUESIA");
ALTER TABLE "ZLISTAS" ADD CONSTRAINT ZLISTAS_DISTRITO_PARTIDO_PK PRIMARY KEY("DISTRITO", "PARTIDO");
ALTER TABLE "ZPARTICIPACOES" ADD CONSTRAINT ZPARTICIPACOES_DISTRITO_PK PRIMARY KEY("DISTRITO");

ALTER TABLE "ZCONCELHOS" 
ADD CONSTRAINT ZCONCELHOS_DISTRITO_FK FOREIGN KEY("DISTRITO") REFERENCES "ZDISTRITOS"("CODIGO");

ALTER TABLE "ZFREGUESIAS" 
ADD CONSTRAINT ZFREGUESIAS_CONCELHO_FK FOREIGN KEY("CONCELHO") REFERENCES "ZCONCELHOS"("CODIGO");

ALTER TABLE "ZVOTACOES" 
ADD CONSTRAINT ZVOTACOES_PARTIDO_FK FOREIGN KEY("PARTIDO") REFERENCES "ZPARTIDOS"("SIGLA"),
ADD CONSTRAINT ZVOTACOES_FREGUESIA_FK FOREIGN KEY("FREGUESIA") REFERENCES "ZFREGUESIAS"("CODIGO");

ALTER TABLE "ZLISTAS" 
ADD CONSTRAINT ZLISTAS_DISTRITO_FK FOREIGN KEY("DISTRITO") REFERENCES "ZDISTRITOS"("CODIGO"),
ADD CONSTRAINT ZLISTAS_PARTIDO_FK FOREIGN KEY("PARTIDO") REFERENCES "ZPARTIDOS"("SIGLA");

ALTER TABLE "ZPARTICIPACOES" 
ADD CONSTRAINT ZPARTICIPACOES_DISTRITO_FK FOREIGN KEY("DISTRITO") REFERENCES "ZDISTRITOS"("CODIGO");

--INDEX

CREATE INDEX ZVOTACOES_PARTIDO_FREGUESIA_IDX ON ZVOTACOES(PARTIDO, FREGUESIA);
CREATE INDEX ZPARTIDOS_SIGLA_IDX ON ZPARTIDOS(SIGLA);
CREATE INDEX ZLISTAS_DISTRITO_PARTIDO_IDX ON ZLISTAS(DISTRITO, PARTIDO);
CREATE INDEX ZCONCELHOS_DISTRITO_IDX ON ZCONCELHOS(DISTRITO);
CREATE INDEX ZFREGUESIAS_CONCELHO_IDX ON ZFREGUESIAS(CONCELHO);
CREATE INDEX ZVOTACOES_PARTIDO_VOTOS_IDX ON ZVOTACOES(PARTIDO, VOTOS);