CREATE TABLE zdistritos AS SELECT * FROM GTD7.distritos;
CREATE TABLE zconcelhos AS SELECT * FROM GTD7.concelhos;
CREATE TABLE zfreguesias AS SELECT * FROM GTD7.freguesias;
CREATE TABLE zpartidos AS SELECT * FROM GTD7.partidos;
CREATE TABLE zvotacoes AS SELECT * FROM GTD7.votacoes;
CREATE TABLE zlistas AS SELECT * FROM GTD7.listas;
CREATE TABLE zparticipacoes AS SELECT * FROM GTD7.participacoes;

ALTER TABLE "ZDISTRITOS" ADD CONSTRAINT ZDISTRITOS_CODIGO_PK PRIMARY KEY("CODIGO");
ALTER TABLE "ZCONCELHOS" ADD CONSTRAINT ZCONCELHOS_CODIGO_PK PRIMARY KEY("CODIGO");
ALTER TABLE "ZFREGUESIAS" ADD CONSTRAINT ZFREGUESIAS_CODIGO_PK PRIMARY KEY("CODIGO");
ALTER TABLE "ZPARTIDOS" ADD CONSTRAINT ZPARTIDOS_SIGLA_PK PRIMARY KEY("SIGLA");
ALTER TABLE "ZVOTACOES" ADD CONSTRAINT ZVOTACOES_PARTIDO_FREGUESIA_PK PRIMARY KEY("PARTIDO", "FREGUESIA");
ALTER TABLE "ZLISTAS" ADD CONSTRAINT ZLISTAS_DISTRITO_PARTIDO_PK PRIMARY KEY("DISTRITO", "PARTIDO");
ALTER TABLE "ZPARTICIPACOES" ADD CONSTRAINT ZPARTICIPACOES_DISTRITO_PK PRIMARY KEY("DISTRITO");

ALTER TABLE "ZCONCELHOS" ADD CONSTRAINT ZCONCELHOS_DISTRITO_FK FOREIGN KEY("DISTRITO") REFERENCES "ZDISTRITOS"("CODIGO");

ALTER TABLE "ZFREGUESIAS" ADD CONSTRAINT ZFREGUESIAS_CONCELHO_FK FOREIGN KEY("CONCELHO") REFERENCES "ZCONCELHOS"("CODIGO");

ALTER TABLE "ZVOTACOES" ADD CONSTRAINT ZVOTACOES_PARTIDO_FK FOREIGN KEY("PARTIDO") REFERENCES "ZPARTIDOS"("SIGLA");
ALTER TABLE "ZVOTACOES" ADD CONSTRAINT ZVOTACOES_FREGUESIA_FK FOREIGN KEY("FREGUESIA") REFERENCES "ZFREGUESIAS"("CODIGO");

ALTER TABLE "ZLISTAS" ADD CONSTRAINT ZLISTAS_DISTRITO_FK FOREIGN KEY("DISTRITO") REFERENCES "ZDISTRITOS"("CODIGO");
ALTER TABLE "ZLISTAS" ADD CONSTRAINT ZLISTAS_PARTIDO_FK FOREIGN KEY("PARTIDO") REFERENCES "ZPARTIDOS"("SIGLA");

ALTER TABLE "ZPARTICIPACOES" ADD CONSTRAINT ZPARTICIPACOES_DISTRITO_FK FOREIGN KEY("DISTRITO") REFERENCES "ZDISTRITOS"("CODIGO");

--INDEX
CREATE INDEX IDX_FREGUESIAS_CONCELHO ON ZFREGUESIAS(CONCELHO);
CREATE INDEX IDX_CONCELHOS_DISTRITO ON ZCONCELHOS(DISTRITO);
CREATE INDEX IDX_CONCELHOS_NOME ON ZCONCELHOS(NOME);
CREATE INDEX IDX_VOTACOES_FREGUESIA_VOTOS ON ZVOTACOES(FREGUESIA, VOTOS DESC);
CREATE INDEX IDX_VOTACOES_PARTIDO_FREGUESIA ON ZVOTACOES(PARTIDO, FREGUESIA, VOTOS);
CREATE INDEX IDX_ZVOTACOES_PARTIDO_VOTOS ON ZVOTACOES(PARTIDO, VOTOS);

-- BITMAP INDEX (OPTIONAL)
CREATE BITMAP INDEX BM_IDX_CONCELHOS_DISTRITO ON ZCONCELHOS(DISTRITO);
CREATE BITMAP INDEX BM_IDX_VOTACOES_PARTIDO ON ZVOTACOES(PARTIDO);

-- DROP
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE zparticipacoes CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE zlistas CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE zvotacoes CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE zpartidos CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE zfreguesias CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE zconcelhos CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE zdistritos CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('One or more tables did not exist or failed to drop.');
END;
/


