CREATE TABLE xdistritos AS SELECT * FROM GTD7.distritos;
CREATE TABLE xconcelhos AS SELECT * FROM GTD7.concelhos;
CREATE TABLE xfreguesias AS SELECT * FROM GTD7.freguesias;
CREATE TABLE xpartidos AS SELECT * FROM GTD7.partidos;
CREATE TABLE xvotacoes AS SELECT * FROM GTD7.votacoes;
CREATE TABLE xlistas AS SELECT * FROM GTD7.listas;
CREATE TABLE xparticipacoes AS SELECT * FROM GTD7.participacoes;

-- DROP
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE xparticipacoes CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE xlistas CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE xvotacoes CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE xpartidos CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE xfreguesias CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE xconcelhos CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE xdistritos CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('One or more tables did not exist or failed to drop.');
END;
/